#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/ekkya/neuron/nrn-7.5"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/ekkya/neuron/nrn-7.5/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/ekkya/Documents/Project_updated/L5_DBC_cACint209_4/x86_64/.libs/libnrnmech.so" "$@"
